import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import * as fs from "node:fs";
import * as path from "node:path";

const PLAN_FILE = ".pi/plan.md";

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "submit_plan",
    label: "Submit Plan",
    description: "Submit a structured implementation plan for user confirmation. Blocks until the user approves or rejects. Only proceed with implementation after approval.",
    promptSnippet: "Submit a step-by-step plan for user review and approval before making changes",
    promptGuidelines: [
      "Use submit_plan BEFORE making any file changes when the user asks for implementation, refactoring, or non-trivial edits.",
      "submit_plan blocks until the user confirms. Do not call other tools while waiting.",
    ],
    parameters: Type.Object({
      title: Type.String({ description: "Short title for the plan" }),
      steps: Type.Array(
        Type.Object({
          description: Type.String({ description: "What this step does" }),
          files: Type.Optional(Type.Array(Type.String({ description: "Files to read or modify" }))),
          command: Type.Optional(Type.String({ description: "Command to validate this step, if any" })),
        }),
        { description: "Ordered list of implementation steps" }
      ),
    }),
    async execute(_toolCallId, params, _signal, onUpdate, ctx) {
      const planPath = path.resolve(ctx.cwd, PLAN_FILE);
      fs.mkdirSync(path.dirname(planPath), { recursive: true });

      // Build formatted plan
      let planText = `# Plan: ${params.title}\n\n`;
      params.steps.forEach((step, i) => {
        planText += `## Step ${i + 1}: ${step.description}\n`;
        if (step.files?.length) {
          planText += `- **Files**: ${step.files.join(", ")}\n`;
        }
        if (step.command) {
          planText += `- **Command**: \`${step.command}\`\n`;
        }
        planText += `\n`;
      });
      planText += `---\n*Plan generated by plan-execute workflow*\n`;

      fs.writeFileSync(planPath, planText, "utf-8");

      onUpdate?.({
        content: [{ type: "text", text: `Plan saved to ${PLAN_FILE}. Awaiting user confirmation...` }],
      });

      const confirmed = await ctx.ui.confirm(
        `Approve plan: ${params.title}`,
        planText + "\nDo you approve this plan? The assistant will implement it step by step after confirmation."
      );

      if (confirmed) {
        return {
          content: [{
            type: "text",
            text: `✅ Plan "${params.title}" approved by user.\n\nImplement the plan step by step. After all steps are complete, run the project's validation command (e.g., npm test, cargo test, pytest) and report the results.`,
          }],
          details: { approved: true, planPath },
        };
      } else {
        try { fs.unlinkSync(planPath); } catch {}
        return {
          content: [{
            type: "text",
            text: `❌ Plan "${params.title}" rejected by user. Ask the user what to change and submit a revised plan.`,
          }],
          details: { approved: false },
        };
      }
    },
  });

  pi.registerTool({
    name: "validate_changes",
    label: "Validate Changes",
    description: "Signal that implementation is complete and validation should run. Use after finishing all plan steps to run tests, lint, typecheck, etc.",
    promptSnippet: "Run project validation (tests, lint, typecheck) after implementation is complete",
    parameters: Type.Object({
      commands: Type.Array(Type.String(), { description: "Validation commands to run (e.g., ['npm test', 'npm run lint'])" }),
    }),
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      const cmdList = params.commands.map(c => `- ${c}`).join("\n");
      return {
        content: [{
          type: "text",
          text: `Validation requested. Run these commands using the bash tool and report results to the user:\n\n${cmdList}\n\nIf any command fails, fix the issues before finishing.`,
        }],
        details: { commands: params.commands },
      };
    },
  });

  pi.registerCommand("clear-plan", {
    description: "Remove the current plan file",
    handler: async (_args, ctx) => {
      const planPath = path.resolve(ctx.cwd, PLAN_FILE);
      try {
        fs.unlinkSync(planPath);
        ctx.ui.notify("Plan file removed", "info");
      } catch {
        ctx.ui.notify("No plan file found", "warning");
      }
    },
  });
}
